### PR TITLE
Update Grpc.Core to version 2.44.0

### PR DESCRIPTION
**Pull request by RomainNeup**
Update the .dylib file to version 2.44.0

### CODE REVIEW

**Comment by ogxd** [comment]
For context, @RomainNeup, myself and probably many other developers today are still using `Grpc.Core` (and MacBooks with ARM chips).    
Despite [this communication](https://grpc.io/blog/grpc-csharp-future/) where Grpc.Core was said to go deprecated on May 2022, the Google Grpc group, given the user feedback, [went back on this and extended the maintenance until May 2023.](https://groups.google.com/g/grpc-io/c/OTj5mb1qzb0). Unfortunately, [they refuse to officially support Grpc.Core for M1](https://github.com/grpc/grpc/issues/32000#issuecomment-1400310851), and this is why we would like to upgrade the binary in this package.

**Comment by drew-512** [comment]
@ogxd and @RomainNeup -- many thinks for championing what is important to those of us using Grpc and the whys behind that choice.  Quite strange to me they don't take on M1 support and leaves me scratching my head.  Anyway, thanks again gentlemen and @ogxd great job at engaging tattermusch on this issue. 

@einari -- merge this?  LGTM.  Doing so also shows that there is a plurality of people that care about this, including anyone using grpc that ships on Unity.

**Comment by einari** [comment]
Sorry I didn't see this before now. Thanks for the PR. I've released it as well on NuGet: https://www.nuget.org/packages/Contrib.Grpc.Core.M1/2.44.0

**Comment by einari** [comment]
I've gone and done for the latest as of today as well 2.46.6.   I'm going to look into creating a workflow that runs daily to update this.

**Pull request merged**
